manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: maaao
      url-base: https://github.com/maaao
    - name: msfmfjt
      url-base: https://github.com/msfmfjt
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-duplex-matrix-driver
      remote: maaao
      revision: master
    - name: zmk-adns5050-driver
      remote: msfmfjt
      revision: main
  self:
    path: config
